<a href="https://colab.research.google.com/github/ezhinani/techassigmentml/blob/main/techassigment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [ ]:
df = pd.read_csv('ai4i2020.csv')

In [ ]:
#Untuk melihat 5 baris teratas dari sebuah data.
df.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1551         42.8                0                0    0   
1                    1408         46.3                3                0    0   
2                    1498         49.4                5                0    0   
3                    1433         39.5                7                0    0   
4                    1408         40.0                9                0    0   

   HDF  PWF  OSF  RNF  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0

In [ ]:
#Untuk mengetahui jumlah baris dan kolom dalam tabel data.
df.shape

(10000, 14)

In [ ]:

#Untuk menampilkan data ringkas dalam DataFrame.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   UDI                      10000 non-null  int64  
 1   Product ID               10000 non-null  object 
 2   Type                     10000 non-null  object 
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64  
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64  
 8   Machine failure          10000 non-null  int64  
 9   TWF                      10000 non-null  int64  
 10  HDF                      10000 non-null  int64  
 11  PWF                      10000 non-null  int64  
 12  OSF                      10000 non-null  int64  
 13  RNF                      10000 non-null  int64  
dtypes: float64(3), int64(9)

In [ ]:

#Untuk memberikan ringkasan statistik dari DataFrame untuk kolom numerik secara default.
df.describe()

UDI  Air temperature [K]  Process temperature [K]  \
count  10000.00000         10000.000000             10000.000000   
mean    5000.50000           300.004930               310.005560   
std     2886.89568             2.000259                 1.483734   
min        1.00000           295.300000               305.700000   
25%     2500.75000           298.300000               308.800000   
50%     5000.50000           300.100000               310.100000   
75%     7500.25000           301.500000               311.100000   
max    10000.00000           304.500000               313.800000   

       Rotational speed [rpm]   Torque [Nm]  Tool wear [min]  Machine failure  \
count            10000.000000  10000.000000     10000.000000     10000.000000   
mean              1538.776100     39.986910       107.951000         0.033900   
std                179.284096      9.968934        63.654147         0.180981   
min               1168.000000      3.800000         0.000000         0.000000   
25%               1423.000000     33.200000        53.000000         0.000000   
50%               1503.000000     40.100000       108.000000         0.000000   
75%               1612.000000     46.800000       162.000000         0.000000   
max               2886.000000     76.600000       253.000000         1.000000   

                TWF           HDF           PWF           OSF          RNF  
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.00000  
mean       0.004600      0.011500      0.009500      0.009800      0.00190  
std        0.067671      0.106625      0.097009      0.098514      0.04355  
min        0.000000      0.000000      0.000000      0.000000      0.00000  
25%        0.000000      0.000000      0.000000      0.000000      0.00000  
50%        0.000000      0.000000      0.000000      0.000000      0.00000  
75%        0.000000      0.000000      0.000000      0.000000      0.00000  
max        1.000000      1.000000      1.000000      1.000000      1.00000

In [ ]:

#Digunakan untuk menghitung jumlah nilai null di setiap kolom dalam DataFrame.
df.isnull().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [ ]:

#Digunakan untuk mengidentifikasi baris duplikat dalam DataFrame.
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [ ]:

#Digunakan untuk menghitung jumlah baris duplikat dalam DataFrame.
df.duplicated().sum()

0

In [ ]:

#Digunakan untuk menghapus kolom-kolom yang disebutkan dari DataFrame
df.drop(['UDI','Product ID','TWF'], axis=1, inplace=True)

In [ ]:

#Digunakan untuk menghapus kolom-kolom yang disebutkan dari DataFrame
df.drop(['Type', 'HDF', 'PWF', 'OSF', 'RNF'], axis=1, inplace=True)

In [ ]:

#Untuk melihat 5 baris teratas dari sebuah data.
df.head()

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0                298.1                    308.6                    1551   
1                298.2                    308.7                    1408   
2                298.1                    308.5                    1498   
3                298.2                    308.6                    1433   
4                298.2                    308.7                    1408   

   Torque [Nm]  Tool wear [min]  Machine failure  
0         42.8                0                0  
1         46.3                3                0  
2         49.4                5                0  
3         39.5                7                0  
4         40.0                9                0

In [ ]:
Input_columns = ['Air temperature [K]' , 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']

In [ ]:
Output_columns = ['Machine failure']

In [ ]:
X = df[Input_columns]
y = df[Output_columns]

In [ ]:

#Untuk menampilkan 5 data teratas.
X.head()

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0                298.1                    308.6                    1551   
1                298.2                    308.7                    1408   
2                298.1                    308.5                    1498   
3                298.2                    308.6                    1433   
4                298.2                    308.7                    1408   

   Torque [Nm]  Tool wear [min]  
0         42.8                0  
1         46.3                3  
2         49.4                5  
3         39.5                7  
4         40.0                9

In [ ]:

#Untuk menampilkan 5 data teratas.
y.head()

Machine failure
0                0
1                0
2                0
3                0
4                0

In [ ]:

#Digunakan untuk membagi dataset menjadi data pelatihan dan data pengujian.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:

#Perintah untuk membuat sebuah instance dari kelas LinearRegression.
lin_reg = LinearRegression()

In [ ]:

#Digunakan untuk melatih (fit) model regresi linier pada data pelatihan.
lin_reg.fit(X_train, y_train)

LinearRegression()

In [ ]:

#Digunakan untuk menampilkan koefisien dan intersep (intercept) dari model regresi linier.
print(lin_reg.coef_)
print(lin_reg.intercept_)

[[ 0.02126815 -0.02074859  0.00051643  0.0118958   0.00028413]]
[-1.21542514]


In [ ]:

#Digunakan untuk mengevaluasi kinerja model regresi linier pada data pengujian.
lin_reg.score(X_test, y_test)

0.1025389942262982

In [ ]:

#Digunakan untuk membuat dan melatih model decision tree untuk klasifikasi.
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:

#Digunakan untuk membuat prediksi kelas target berdasarkan fitur-fitur dalam data pengujian menggunakan model pohon keputusan yang telah dilatih.
y_pred = clf.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(f'Akurasi: {accuracy}')
print('Classification Report:')
print(classification_report(y_test, y_pred))
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Akurasi: 0.977
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1933
           1       0.66      0.66      0.66        67

    accuracy                           0.98      2000
   macro avg       0.82      0.82      0.82      2000
weighted avg       0.98      0.98      0.98      2000

Confusion Matrix:
[[1910   23]
 [  23   44]]


In [ ]:
#Digunakan untuk evaluasi model Decission Tree nilai precision 80% recall 80% acc78%
y_pred = clf.predict(X_test)

In [ ]:
#Digunakan untuk mengevaluasi kinerja model.
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

In [ ]:
print(f'Akurasi: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print('Classification Report:')
print(classification_report(y_test, y_pred))
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Akurasi: 0.98
Precision: 0.98
Recall: 0.98
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1933
           1       0.66      0.66      0.66        67

    accuracy                           0.98      2000
   macro avg       0.82      0.82      0.82      2000
weighted avg       0.98      0.98      0.98      2000

Confusion Matrix:
[[1910   23]
 [  23   44]]


In [ ]:
log_reg = LogisticRegression(max_iter=1000, random_state=42)
log_reg.fit(X_train, y_train)

c:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(max_iter=1000, random_state=42)

In [ ]:
y_pred = log_reg.predict(X_test)


In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(f'Akurasi: {accuracy}')
print('Classification Report:')
print(classification_report(y_test, y_pred))
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Akurasi: 0.968
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1933
           1       0.62      0.12      0.20        67

    accuracy                           0.97      2000
   macro avg       0.79      0.56      0.59      2000
weighted avg       0.96      0.97      0.96      2000

Confusion Matrix:
[[1928    5]
 [  59    8]]


In [ ]:
#Digunakan untuk evaluasi model log reg precision 78% recall 80% acc 78%
y_pred = log_reg.predict(X_test)

In [ ]:
#Digunakan untuk mengevaluasi kinerja model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

In [ ]:
print(f'Akurasi: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print('Classification Report:')
print(classification_report(y_test, y_pred))
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Akurasi: 0.97
Precision: 0.96
Recall: 0.97
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1933
           1       0.62      0.12      0.20        67

    accuracy                           0.97      2000
   macro avg       0.79      0.56      0.59      2000
weighted avg       0.96      0.97      0.96      2000

Confusion Matrix:
[[1928    5]
 [  59    8]]


In [ ]:
#Untuk melatih model Decision Tree.
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)
y_pred_dt = clf.predict(X_test)

#Untuk melatih model Logistic Regression.
log_reg = LogisticRegression(max_iter=1000, random_state=42)
log_reg.fit(X_train, y_train)
y_pred_lr = log_reg.predict(X_test)

c:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
#Digunakan untuk evaluasi Decision Tree.
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt, average='weighted')
recall_dt = recall_score(y_test, y_pred_dt, average='weighted')

#Digunakan untuk evaluasi Logistic Regression.
accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr, average='weighted')
recall_lr = recall_score(y_test, y_pred_lr, average='weighted')

In [ ]:
print("Decision Tree Evaluation")
print(f'Akurasi: {accuracy_dt:.2f}')
print(f'Precision: {precision_dt:.2f}')
print(f'Recall: {recall_dt:.2f}')
print('Classification Report:')
print(classification_report(y_test, y_pred_dt))
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred_dt))

print("\nLogistic Regression Evaluation")
print(f'Akurasi: {accuracy_lr:.2f}')
print(f'Precision: {precision_lr:.2f}')
print(f'Recall: {recall_lr:.2f}')
print('Classification Report:')
print(classification_report(y_test, y_pred_lr))
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred_lr))

Decision Tree Evaluation
Akurasi: 0.98
Precision: 0.98
Recall: 0.98
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1933
           1       0.66      0.66      0.66        67

    accuracy                           0.98      2000
   macro avg       0.82      0.82      0.82      2000
weighted avg       0.98      0.98      0.98      2000

Confusion Matrix:
[[1910   23]
 [  23   44]]

Logistic Regression Evaluation
Akurasi: 0.97
Precision: 0.96
Recall: 0.97
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1933
           1       0.62      0.12      0.20        67

    accuracy                           0.97      2000
   macro avg       0.79      0.56      0.59      2000
weighted avg       0.96      0.97      0.96      2000

Confusion Matrix:
[[1928    5]
 [  59    8]]
